# Training Configuration
training:
  model_name: "microsoft/layoutlm-base-uncased"
  max_seq_length: 512
  learning_rate: 5e-5
  batch_size: 2
  num_epochs: 5
  warmup_steps: 100
  weight_decay: 0.01
  
# Data Configuration
data:
  max_len: 510
  train_split: "train"
  test_split: "test"
  labels_file: "data/processed/labels.txt"
  
# Model Configuration
model:
  num_labels: null  # Will be set automatically based on labels file
  device: "cuda"  # Change to "cpu" if no GPU available
  
# Paths
paths:
  data_dir: "data/processed"
  model_save_dir: "models/checkpoints"
  logs_dir: "models/logs"
  
# API Configuration
api:
  host: "0.0.0.0"
  port: 5000
  debug: true
  upload_folder: "data/sample/uploads"